---
# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

- hosts: all
  vars_files:
    - vars/stack-config.yml
  vars:
    action: "{{ operation }}"
    home_dir: "{{ home_path }}"
  pre_tasks:
    - raw: "apt-get -qqy update && apt-get install -qqy python-minimal python-pip || dnf -y install python27 || which python"
    - name: Gathering Facts
      setup: #aka gather_facts
  roles:
    - tendermint
    - planetmint
    - mongodb
    - { role: docker, when: stack_type|lower == "docker" or stack_type|lower == "cloud" }
