# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

version: '2.2'

services:
  planetmint_1:
    build:
      context: .
      dockerfile: Dockerfile-all-in-one
    expose:
      - "9984"
      - "9985"
      - "26656"
      - "26657"
      - "26658"
    environment:
      ME: "planetmint_1"
      OTHER: "planetmint_2"
    command: ["/usr/src/app/scripts/clean-shared.sh", "/usr/src/app/pkg/scripts/all-in-one.bash"]
    volumes:
      - ./scripts/genesis.py:/usr/src/app/scripts/genesis.py
      - ./scripts/clean-shared.sh:/usr/src/app/scripts/clean-shared.sh
      - ./scripts/wait-for-config.sh:/usr/src/app/scripts/wait-for-config.sh
      - ./pkg/scripts/all-in-one.bash:/usr/src/app/scripts/all-in-one.bash
      - shared:/shared

  planetmint_2:
    build:
      context: .
      dockerfile: Dockerfile-all-in-one
    expose:
      - "9984"
      - "9985"
      - "26656"
      - "26657"
      - "26658"
    environment:
      ME: "planetmint_2"
      OTHER: "planetmint_1"
    command: /usr/src/app/pkg/scripts/all-in-one.bash
    volumes:
      - ./scripts/genesis.py:/usr/src/app/scripts/genesis.py
      - ./scripts/clean-shared.sh:/usr/src/app/scripts/clean-shared.sh
      - ./scripts/wait-for-config.sh:/usr/src/app/scripts/wait-for-config.sh
      - ./pkg/scripts/all-in-one.bash:/usr/src/app/scripts/all-in-one.bash
      - shared:/shared

  test:
    build:
      context: .
      dockerfile: integration/python/Dockerfile
    depends_on:
      - planetmint_1
      - planetmint_2
    environment:
      PLANETMINT_ENDPOINT_1: planetmint_1
      PLANETMINT_ENDPOINT_2: planetmint_2
    command: ["/scripts/wait-for-planetmint.sh", "pytest", "/src"]
    volumes:
      - ./integration/python/src:/src
      - ./scripts/wait-for-planetmint.sh:/scripts/wait-for-planetmint.sh


volumes:
  shared:
