FROM python:3.9-slim
LABEL maintainer "contact@ipdb.global"

ARG TM_VERSION=0.34.15
RUN mkdir -p /usr/src/app
ENV HOME /root
COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN apt-get update \
    && apt-get install -y openssl ca-certificates git \
    && apt-get install -y vim build-essential cmake jq zsh wget \
    && apt-get install -y libstdc++6 \
    && apt-get install -y openssh-client openssh-server \
    && pip install --upgrade pip cffi \
    && pip install -e . \
    && apt-get autoremove

# Install tarantool and monit
RUN apt-get install -y dirmngr gnupg apt-transport-https software-properties-common ca-certificates curl
RUN apt-get update
RUN curl -L https://tarantool.io/wrATeGF/release/2/installer.sh | bash 
RUN apt-get install -y tarantool monit

# Install Tendermint
RUN wget https://github.com/tendermint/tendermint/releases/download/v${TM_VERSION}/tendermint_${TM_VERSION}_linux_amd64.tar.gz \
    && tar -xf tendermint_${TM_VERSION}_linux_amd64.tar.gz \
    && mv tendermint /usr/local/bin/ \
    && rm tendermint_${TM_VERSION}_linux_amd64.tar.gz

ENV TMHOME=/tendermint

# Planetmint enviroment variables
ENV PLANETMINT_DATABASE_PORT 3303
ENV PLANETMINT_DATABASE_BACKEND tarantool_db
ENV PLANETMINT_DATABASE_HOST localhost
ENV PLANETMINT_SERVER_BIND 0.0.0.0:9984
ENV PLANETMINT_WSSERVER_HOST 0.0.0.0
ENV PLANETMINT_WSSERVER_SCHEME ws

ENV PLANETMINT_WSSERVER_ADVERTISED_HOST 0.0.0.0
ENV PLANETMINT_WSSERVER_ADVERTISED_SCHEME ws
ENV PLANETMINT_TENDERMINT_PORT 26657

VOLUME /data/db /data/configdb /tendermint

EXPOSE 27017 28017 9984 9985 26656 26657 26658

RUN pip install pynacl==1.4.0 base58==2.1.1 pyasn1==0.4.8 zenroom==2.1.0.dev1655293214 cryptography==3.4.7


WORKDIR $HOME